# Generated by Django 4.2.6 on 2023-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="usersearch",
            name="search_terms",
            field=models.TextField(),
        ),
    ]
