# Generated by Django 4.2.6 on 2023-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_newsarticle_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.TextField(),
        ),
    ]
