# Generated by Django 4.2.6 on 2023-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_newsarticle_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.TextField(null=True),
        ),
    ]
