# Generated by Django 4.2.6 on 2023-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_redditarticle_k3_redditarticle_k2_redditarticle_k1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle_k1",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle_k2",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle_k3",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="redditarticle_k1",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="redditarticle_k2",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="redditarticle_k3",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
    ]
