# Generated by Django 4.2.6 on 2023-10-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_rename_description_newsarticle_k1_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle_k1",
            name="keyword",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="newsarticle_k2",
            name="keyword",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="newsarticle_k3",
            name="keyword",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k1",
            name="keyword",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k2",
            name="keyword",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k3",
            name="keyword",
            field=models.TextField(null=True),
        ),
    ]
