# Generated by Django 4.2.6 on 2023-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_newsarticle_k1_keyword_newsarticle_k2_keyword_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle_k1",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newsarticle_k1",
            name="content",
        ),
        migrations.RemoveField(
            model_name="newsarticle_k2",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newsarticle_k2",
            name="content",
        ),
        migrations.RemoveField(
            model_name="newsarticle_k3",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newsarticle_k3",
            name="content",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k1",
            name="author",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k1",
            name="content",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k2",
            name="author",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k2",
            name="content",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k3",
            name="author",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k3",
            name="content",
        ),
        migrations.AddField(
            model_name="newsarticle_k1",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="newsarticle_k2",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="newsarticle_k3",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="redditarticle_k1",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="redditarticle_k2",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="redditarticle_k3",
            name="data",
            field=models.JSONField(default=list),
        ),
    ]
