# Generated by Django 4.2.6 on 2023-10-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_remove_newsarticle_k1_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redditarticle_k1",
            name="data",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k2",
            name="data",
        ),
        migrations.RemoveField(
            model_name="redditarticle_k3",
            name="data",
        ),
        migrations.AddField(
            model_name="redditarticle_k1",
            name="author",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k1",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k2",
            name="author",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k2",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k3",
            name="author",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redditarticle_k3",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
