# Generated by Django 4.2.6 on 2023-10-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_newsarticle_k1_sentiments_newsarticle_k2_sentiments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="total_sentiments",
            field=models.JSONField(default=None),
        ),
    ]
