# Generated by Django 4.2.6 on 2023-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_alter_usersearch_total_sentiments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle_k1",
            name="sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle_k2",
            name="sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle_k3",
            name="sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="redditarticle_k1",
            name="sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="redditarticle_k2",
            name="sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="redditarticle_k3",
            name="sentiments",
            field=models.JSONField(default=None, null=True),
        ),
    ]
