# Generated by Django 4.2.6 on 2023-10-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_alter_newsarticle_k1_sentiments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="count",
            field=models.JSONField(default=None, null=True),
        ),
    ]
