# Generated by Django 4.2.6 on 2023-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_alter_usersearch_total_sentiments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersearch",
            name="total_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
    ]
