# Generated by Django 4.2.6 on 2023-10-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_alter_usersearch_total_sentiments"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="keyword_total_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
    ]
