# Generated by Django 4.2.6 on 2023-10-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_usersearch_keyword_total_sentiments"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="total_news_responses",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="usersearch",
            name="total_reddit_responses",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="usersearch",
            name="search_terms",
            field=models.TextField(null=True),
        ),
    ]
