# Generated by Django 4.2.6 on 2023-10-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "myapp",
            "0024_rename_keyword_total_sentiments_usersearch_each_keyword_total_sentiments",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Reddit_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_terms", models.TextField(null=True)),
                ("K1_reddit_data", models.JSONField(default=list)),
                ("K1_reddit_sentiments", models.JSONField(default=None, null=True)),
                ("K2_reddit_data", models.JSONField(default=list)),
                ("K2_reddit_sentiments", models.JSONField(default=None, null=True)),
                ("K3_reddit_data", models.JSONField(default=list)),
                ("K3_reddit_sentiments", models.JSONField(default=None, null=True)),
                (
                    "each_keyword_reddit_sentiments",
                    models.JSONField(default=None, null=True),
                ),
                ("reddit_total_sentiments", models.JSONField(default=None, null=True)),
                (
                    "user_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.usersearch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News_Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_terms", models.TextField(null=True)),
                ("K1_news_data", models.JSONField(default=list)),
                ("K1_news_sentiments", models.JSONField(default=None, null=True)),
                ("K2_news_data", models.JSONField(default=list)),
                ("K2_news_sentiments", models.JSONField(default=None, null=True)),
                ("K3_news_data", models.JSONField(default=list)),
                ("K3_news_sentiments", models.JSONField(default=None, null=True)),
                (
                    "each_keyword_news_sentiments",
                    models.JSONField(default=None, null=True),
                ),
                ("news_total_sentiments", models.JSONField(default=None, null=True)),
                (
                    "user_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.usersearch",
                    ),
                ),
            ],
        ),
    ]
