# Generated by Django 4.2.6 on 2023-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0029_alter_news_articles_k1_news_sentiments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="sentiments_from_news",
            field=models.JSONField(default=None, null=True),
        ),
    ]
