# Generated by Django 4.2.6 on 2023-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0030_usersearch_sentiments_from_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="reddit_comments",
            name="K1_reddit_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reddit_comments",
            name="K2_reddit_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reddit_comments",
            name="K3_reddit_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="reddit_comments",
            name="K1_reddit_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="reddit_comments",
            name="K2_reddit_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="reddit_comments",
            name="K3_reddit_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
