# Generated by Django 4.2.6 on 2023-10-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "myapp",
            "0032_rename_sentiments_from_news_usersearch_each_keyword_sentiments_from_news_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_articles",
            name="K1_news_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="news_articles",
            name="K2_news_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="news_articles",
            name="K3_news_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
