# Generated by Django 4.2.6 on 2023-10-13 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0033_alter_news_articles_k1_news_data_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsArticle_K1",
            new_name="News_Articles_K1",
        ),
        migrations.RenameModel(
            old_name="NewsArticle_K3",
            new_name="News_Articles_K2",
        ),
        migrations.RenameModel(
            old_name="RedditArticle_K2",
            new_name="News_Articles_K3",
        ),
        migrations.RenameModel(
            old_name="RedditArticle_K1",
            new_name="Reddit_Comments_K1",
        ),
        migrations.RenameModel(
            old_name="NewsArticle_K2",
            new_name="Reddit_Comments_K2",
        ),
        migrations.RenameModel(
            old_name="RedditArticle_K3",
            new_name="Reddit_Comments_K3",
        ),
    ]
