# Generated by Django 4.2.6 on 2023-10-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0034_rename_newsarticle_k1_news_articles_k1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="each_keyword_combine_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
