# Generated by Django 4.2.6 on 2023-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0035_usersearch_each_keyword_combine_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="news_articles",
            name="each_keyword_combine_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="news_articles",
            name="each_keyword_total_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reddit_comments",
            name="each_keyword_combine_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reddit_comments",
            name="each_keyword_total_sentiments",
            field=models.JSONField(default=None, null=True),
        ),
    ]
