# Generated by Django 4.2.6 on 2023-10-15 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0036_news_articles_each_keyword_combine_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersearch",
            old_name="total_news_responses",
            new_name="each_keyword_total_news_responses",
        ),
        migrations.RenameField(
            model_name="usersearch",
            old_name="total_reddit_responses",
            new_name="each_keyword_total_reddit_responses",
        ),
    ]
