# Generated by Django 4.2.6 on 2023-10-15 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "myapp",
            "0037_rename_total_news_responses_usersearch_each_keyword_total_news_responses_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news_articles_k1",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="news_articles_k2",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="news_articles_k3",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="reddit_comments_k1",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="reddit_comments_k2",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="reddit_comments_k3",
            name="keyword",
        ),
    ]
