# Generated by Django 4.2.6 on 2023-10-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0040_remove_usersearch_graph_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="graph_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
