# Generated by Django 4.2.6 on 2023-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0041_usersearch_graph_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersearch",
            name="created_at",
            field=models.DateField(),
        ),
    ]
