# Generated by Django 4.2.6 on 2023-10-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0046_usersearch_k1_reddit_graph_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="eachkeyword_news_graph_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
