# Generated by Django 4.2.6 on 2023-10-20 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0047_usersearch_eachkeyword_news_graph_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersearch",
            name="eachkeyword_news_graph_data",
        ),
    ]
